Various shell improvements (#2)
* Use a single command to start yggdrasild immediately
systemctl can both enable and start a service in a single command.

* Do not leak temporary files
This uses a trap to remove temporary files. This avoids leaking
temporary files in case of an early exit.

* Do not spawn subshells in errors
Backticks in shell spawn a subshell. In the first case it would actually
start an infinite loop since it would invoke itself.

* Do not use reserved exit code 2
Exit code 2 is reserved for misuse of shell builtins.

https://tldp.org/LDP/abs/html/exitcodes.html
* Remove SBINDIR variable

Any shell command knows how it was called since it's stored in $0. This
simplifies the logic and makes it portable. It also opens the path to
branding.

* Fail early
Bash supports an exit early mode using set -e. This means it stops
executing whenever a command fails.

diff --git a/katello-pull-transport-migrate b/katello-pull-transport-migrate
--- a/katello-pull-transport-migrate
+++ b/katello-pull-transport-migrate
@@ -1,19 +1,17 @@
-#!/bin/sh
-
-# set SBINDIR to /sbin if it is not set
-if [ -z "$SBINDIR" ]; then
-    SBINDIR=/usr/sbin
-fi
+#!/bin/bash
 
 # check if system is registered
 subscription-manager identity > /dev/null
 if [ $? -ne 0 ]; then
-    echo "Please register with subscription-manager first, then re-run `$SBINDIR/katello-pull-transport-migrate`."
+    echo "Please register with subscription-manager first, then re-run '$0'."
     exit 1
 fi
 
+set -e
+
 echo "Getting configuration from subscription-manager..."
 KPPTEMPFILE=$(mktemp kpp_tempfile_XXXXXXXX)
+trap "rm -f $KPPTEMPFILE" ERR EXIT
 subscription-manager config --list > $KPPTEMPFILE
 CONSUMER_CERT_DIR=$(grep 'consumercertdir' $KPPTEMPFILE | cut -d= -f2 | xargs | sed 's/[][]//g')
 CERT_FILE=$CONSUMER_CERT_DIR/cert.pem
@@ -23,17 +21,15 @@ SERVER_NAME=$(grep 'hostname = ' $KPPTEMPFILE | cut -d= -f2 | xargs | cut -d ' '
 
 # fail if no server name, cert dir, or ca file
 if [ -z "$SERVER_NAME" ] || [ -z "$CONSUMER_CERT_DIR" ] || [ -z "$CA_FILE" ]; then
-    echo "Unable to determine config from `subscription-manager config --list`; exiting"
+    echo "Unable to determine config from 'subscription-manager config --list'; exiting"
     exit 1
 fi
 
 # fail if client is not registered to a Katello
 if ! grep -q 'prefix = \/rhsm' $KPPTEMPFILE; then
     echo "Client is registered to RHSM; exiting"
-    exit 2
+    exit 1
 fi
-
-rm -f $KPPTEMPFILE
 
 # set SYSCONFDIR to /etc if it is not set
 if [ -z "$SYSCONFDIR" ]; then
@@ -56,14 +52,13 @@ log-level = "error"
 EOF
 
 else
-    echo "$SYSCONFDIR/yggdrasil/config.toml not found! Did `yum install yggdrasil` succeed?"
+    echo "$SYSCONFDIR/yggdrasil/config.toml not found! Did 'yum install yggdrasil' succeed?"
     exit 1
 fi
 
 # start the yggdrasild service
 echo "Starting yggdrasild..."
-systemctl enable yggdrasild
-systemctl start yggdrasild
+systemctl enable --now yggdrasild
 
 # check status of yggdrasild and fail if it is not running
 # possible failure reason: incorrect protocol (should be tcp:// or mqtt://) or port (should be 1883)
